import type { PageContent } from "./types";

export const en: PageContent = {
  locale: "en",
  lang: "en",
  htmlLang: "en",
  meta: {
    title: "CR-CIPI | Costa Rican Chamber of International Private Investment",
    description:
      "An independent private-sector initiative bringing together professionals and organizations to attract, facilitate and protect responsible international private investment in Costa Rica.",
  },
  nav: {
    home: "Home",
    about: "About",
    join: "Join",
    volunteer: "Volunteer",
  },
  home: {
    hero: {
      eyebrow: "Costa Rican Chamber of International Private Investment",
      headline: "Attracting responsible international private investment to Costa Rica.",
      body: "CR-CIPI is an independent private-sector initiative bringing together professionals, companies and leaders committed to attracting, facilitating and protecting private investment from international individuals and families who choose Costa Rica to live, retire, invest and build businesses.",
      primaryCta: "Become a Founding Volunteer",
      secondaryCta: "Join the Initiative",
    },
    why: {
      eyebrow: "Why this matters",
      heading: "Complementing corporate investment with private capital",
      body: "Costa Rica has built important mechanisms to attract international corporate investment. CR-CIPI seeks to complement that effort by focusing on another important source of investment: individuals, families, retirees, pensioners, entrepreneurs and private investors who choose Costa Rica as a long-term home and investment destination.",
    },
    vision: "Attract People. Attract Capital. Create Opportunity. Strengthen Costa Rica.",
    priorities: {
      eyebrow: "Our priorities",
      heading: "Four priorities guide our work",
      cards: [
        {
          title: "Attract Investment",
          body: "Promote Costa Rica internationally as a destination to live, invest and establish long-term economic roots.",
        },
        {
          title: "Improve the Investment Environment",
          body: "Identify barriers and promote simpler, clearer and more competitive processes.",
        },
        {
          title: "Protect Investor Confidence",
          body: "Promote transparency, professional standards and responsible practices.",
        },
        {
          title: "Public Policy",
          body: "Develop proposals for legislation and public policy that improve Costa Rica's competitiveness.",
        },
      ],
    },
    founding: {
      eyebrow: "Founding stage",
      heading: "Help build the initiative",
      body: "CR-CIPI is currently in its formation stage. We are looking for professionals, business leaders, academics and institutional partners who want to contribute their expertise and time to help build the initiative.",
      cta: "Become a Founding Volunteer",
    },
  },
  about: {
    hero: {
      eyebrow: "About CR-CIPI",
      heading: "An independent private-sector initiative",
      body: [
        "CR-CIPI is an independent private-sector initiative created to bring together professionals and organizations that believe Costa Rica can become one of the world's leading destinations for responsible international private investment.",
        "Unlike organizations primarily focused on multinational corporations, CR-CIPI focuses on investment generated by individuals and families who choose Costa Rica to live, retire, acquire property, establish businesses and invest their private capital.",
        "Our goal is to build an organized professional ecosystem capable of collaborating with government institutions, legislators, municipalities, chambers, universities and international communities.",
      ],
    },
    mission: {
      eyebrow: "Our mission",
      heading: "Mission",
      body: "To attract, facilitate and protect responsible international private investment while creating long-term economic value for Costa Rica.",
    },
    priorities: {
      eyebrow: "Institutional priorities",
      heading: "Five institutional priorities",
      items: [
        {
          title: "Research & Data",
          description:
            "Measure and communicate the economic impact of international residents and private investors.",
        },
        {
          title: "Public Policy",
          description: "Develop evidence-based public-policy and legislative proposals.",
        },
        {
          title: "Investment Attraction",
          description: "Promote Costa Rica in relevant international markets.",
        },
        {
          title: "Professional Standards",
          description:
            "Promote transparency, ethics and responsible practices across the ecosystem.",
        },
        {
          title: "Collaboration",
          description:
            "Build bridges among private sector, government, academia and international communities.",
        },
      ],
    },
    not: {
      eyebrow: "What we are not",
      heading: "What CR-CIPI is not",
      items: [
        "Not a real-estate company or brokerage.",
        "Not an investment fund or financial advisor.",
        "Not an immigration law firm.",
        "Not a relocation company.",
        "Not a government agency.",
        "Not a platform created to promote the commercial interests of any single member.",
      ],
      positioning:
        "CR-CIPI is a collaborative chamber initiative focused on strengthening Costa Rica's international private-investment ecosystem.",
    },
  },
  join: {
    hero: {
      eyebrow: "Join CR-CIPI",
      heading: "Help Build CR-CIPI",
      body: "CR-CIPI is currently being developed by volunteers. We are looking for professionals who believe Costa Rica can attract significantly more responsible international private investment and who would like to contribute their knowledge, experience and time.",
    },
    committees: {
      eyebrow: "Founding committees",
      heading: "Five founding working committees",
      items: [
        { name: "Public Policy & Legislation Committee" },
        { name: "Investment Attraction Committee" },
        { name: "Research & Economic Impact Committee" },
        { name: "Membership & Partnerships Committee" },
        { name: "Communications & International Promotion Committee" },
      ],
    },
    participation: {
      eyebrow: "Ways to participate",
      heading: "How you can get involved",
      options: [
        {
          title: "Volunteer",
          purpose: "Contribute professional expertise and time.",
        },
        {
          title: "Committee Member",
          purpose: "Participate actively in one of the founding working committees.",
        },
        {
          title: "Founding Member",
          purpose: "Help shape governance, priorities and the initial agenda.",
        },
        {
          title: "Corporate Partner",
          purpose: "Support research, events, operations or international promotion.",
        },
        {
          title: "Government / Institutional Partner",
          purpose: "Collaborate on policy, research and ecosystem development.",
        },
        {
          title: "Academic / Research Partner",
          purpose: "Support data, measurement, studies and evidence-based proposals.",
        },
      ],
    },
    goals: {
      eyebrow: "Founding goals",
      heading: "Our 12-month founding targets",
      items: [
        { metric: "Professionals", target: "100" },
        { metric: "Founding organizations", target: "25" },
        { metric: "Working committees", target: "5" },
        { metric: "Economic impact study", target: "1" },
        { metric: "Public-policy proposals", target: "3" },
      ],
    },
    form: {
      heading: "Volunteer / Interest Form",
      intro:
        "Tell us about yourself and how you would like to contribute. We will be in touch about next steps.",
      fields: {
        firstName: "First Name",
        lastName: "Last Name",
        company: "Company / Organization",
        profession: "Profession / Role",
        email: "Email",
        phone: "Phone / WhatsApp",
        linkedin: "LinkedIn URL",
        expertise: "Area of Expertise",
        participation: "How would you like to participate?",
        reason: "Why are you interested in supporting CR-CIPI?",
        language: "Preferred Language",
        consent: "I agree to be contacted about CR-CIPI.",
        submit: "Submit",
        submitting: "Submitting...",
      },
      expertiseOptions: [
        { value: "law", label: "Law" },
        { value: "immigration", label: "Immigration" },
        { value: "public-policy", label: "Public Policy" },
        { value: "government-relations", label: "Government Relations" },
        { value: "real-estate", label: "Real Estate" },
        { value: "banking", label: "Banking" },
        { value: "investments", label: "Investments" },
        { value: "accounting", label: "Accounting" },
        { value: "tax", label: "Tax" },
        { value: "economics", label: "Economics" },
        { value: "international-trade", label: "International Trade" },
        { value: "development", label: "Development" },
        { value: "tourism", label: "Tourism" },
        { value: "relocation", label: "Relocation" },
        { value: "marketing", label: "Marketing" },
        { value: "communications", label: "Communications" },
        { value: "research", label: "Research" },
        { value: "academia", label: "Academia" },
        { value: "international-relations", label: "International Relations" },
        { value: "other", label: "Other" },
      ],
      participationOptions: [
        { value: "volunteer", label: "Volunteer" },
        { value: "committee-member", label: "Committee Member" },
        { value: "founding-member", label: "Founding Member" },
        { value: "corporate-partner", label: "Corporate Partner" },
        { value: "government-institutional", label: "Government / Institutional Partner" },
        { value: "academic-research", label: "Academic / Research Partner" },
        { value: "other", label: "Other" },
      ],
      languageOptions: [
        { value: "en", label: "English" },
        { value: "es", label: "Spanish" },
      ],
      errors: {
        required: "This field is required.",
        email: "Please enter a valid email address.",
        consent: "Please agree to be contacted to submit the form.",
        generic: "Something went wrong. Please try again.",
      },
      success: {
        title: "Thank you for your interest",
        body: "Your application has been received. We will be in touch about next steps.",
      },
    },
  },
  footer: {
    purpose:
      "An independent private-sector initiative to attract, facilitate and protect responsible international private investment in Costa Rica.",
    contact: "Contact",
    linkedin: "LinkedIn",
    formation:
      "CR-CIPI is currently an initiative under development. Its organizational structure, governance and formal incorporation are being established by its founding participants.",
    rights: "All rights reserved.",
  },
};